# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('NPCluster_rcpp_hello_world', PACKAGE = 'NPCluster')
}

.createEngine <- function(sort) {
    .Call('NPCluster_createEngine', PACKAGE = 'NPCluster', sort)
}

.accessEngine <- function(sexp) {
    .Call('NPCluster_accessEngine', PACKAGE = 'NPCluster', sexp)
}

.computePmfAndNeighborhoods <- function(sexp, n0, nVec, epsilon, epsilon2, K, N, Y, Xsd, rowSubsetI, CmVec, n2, phiV, tau, tau0, maxNeighborhoodSize, cutOff) {
    .Call('NPCluster_computePmfAndNeighborhoods', PACKAGE = 'NPCluster', sexp, n0, nVec, epsilon, epsilon2, K, N, Y, Xsd, rowSubsetI, CmVec, n2, phiV, tau, tau0, maxNeighborhoodSize, cutOff)
}

.computePdpLogLikelihood <- function(sexp, k, X, A, S, G, N, tau, tau0, tauInt, colSums) {
    .Call('NPCluster_computePdpLogLikelihood', PACKAGE = 'NPCluster', sexp, k, X, A, S, G, N, tau, tau0, tauInt, colSums)
}

.fastTabulate <- function(mat, K) {
    .Call('NPCluster_fastTabulate', PACKAGE = 'NPCluster', mat, K)
}

.fastTabulateVector <- function(vec, K, includeZero) {
    .Call('NPCluster_fastTabulateVector', PACKAGE = 'NPCluster', vec, K, includeZero)
}

.fastXtX <- function(rX) {
    .Call('NPCluster_fastXtX', PACKAGE = 'NPCluster', rX)
}

